graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true
  pageTitle: GraphiQL

client:
  holidays:
    address: http://www.holidaywebservice.com/holidayservice_v2/holidayservice2.asmx
